/**
 * E2E test for writer bug fixes:
 * 1. Path mismatch (NOT_FOUND on reload) — writer_root vs sandbox_root
 * 2. Raw research dump in document body — auto-pulses should be events only
 * 3. Persistence across page reload
 *
 * Targets production (choir-ip.com) or local dev via PLAYWRIGHT_HYPERVISOR_BASE_URL.
 */

import { expect, test, type Locator } from "@playwright/test";
import { ensureAuthenticated } from "./auth.helpers";

async function isVisible(locator: Locator): Promise<boolean> {
  try {
    return await locator.isVisible();
  } catch {
    return false;
  }
}

test.describe("writer bugfix verification", () => {
  test("prompt creates writer document, persists on reload, no raw research text", async ({
    page,
  }) => {
    // Step 1: Authenticate
    await ensureAuthenticated(page);
    await page.goto("/");

    // Step 2: Submit a prompt that triggers writer + researcher
    const promptInput = page.getByPlaceholder(/Ask anything, paste URL/i);
    await expect(promptInput).toBeVisible({ timeout: 60_000 });

    const marker = `bugfix_e2e_${Date.now()}`;
    const objective = `Write a short summary about the Rust programming language. marker:${marker}`;
    await promptInput.fill(objective);
    await promptInput.press("Enter");

    // Step 3: Wait for writer window or toast response
    const writerWindowTitle = page
      .locator(".floating-window .window-titlebar span")
      .filter({ hasText: "Writer" })
      .first();
    const toastIndicator = page.locator(".conductor-toast-indicator").first();
    const errorIndicator = page.locator(".conductor-error-indicator").first();

    await expect
      .poll(
        async () => {
          if (await isVisible(writerWindowTitle)) return "writer";
          if (await isVisible(toastIndicator)) return "toast";
          if (await isVisible(errorIndicator)) return "error";
          return "pending";
        },
        { timeout: 120_000, intervals: [500, 1000, 1500, 2000] }
      )
      .not.toBe("pending");

    const currentState = await (async () => {
      if (await isVisible(writerWindowTitle)) return "writer";
      if (await isVisible(toastIndicator)) return "toast";
      if (await isVisible(errorIndicator)) return "error";
      return "pending";
    })();

    expect(currentState).not.toBe("error");

    await page.screenshot({
      path: "../artifacts/playwright/writer-bugfix-after-prompt.png",
      fullPage: true,
    });

    if (currentState === "writer") {
      // Step 4: Wait for "Loading document..." banner to disappear and prose body to have content.
      // The conductor + workers need time to generate content via LLM calls.
      const loadingBanner = page.locator("text=Loading document...").first();
      const writerBody = page.locator(".writer-prose-body").first();

      // Wait for loading to finish (content generated by LLM) — up to 2 minutes
      await expect
        .poll(
          async () => {
            const loading = await isVisible(loadingBanner);
            const bodyVisible = await isVisible(writerBody);
            const bodyText = bodyVisible
              ? ((await writerBody.textContent()) ?? "")
              : "";
            if (!loading && bodyText.length > 10) return "ready";
            if (bodyText.length > 10) return "ready";
            return "loading";
          },
          { timeout: 120_000, intervals: [2000, 3000, 5000] }
        )
        .toBe("ready");

      await page.screenshot({
        path: "../artifacts/playwright/writer-bugfix-writer-content.png",
        fullPage: true,
      });

      // Step 5: Verify NO raw research pulse text in document body
      const bodyText = (await writerBody.textContent()) ?? "";
      expect(bodyText).not.toContain("Research pulse for");
      expect(bodyText).not.toContain("Fetched source:");
      expect(bodyText).not.toContain("Emerging concepts:");
      expect(bodyText).not.toContain("researcher_auto_search_pulse");
      expect(bodyText).not.toContain("researcher_auto_fetch_pulse");

      // Step 6: Reload the page and verify document persists (bug #1 + #3 fix)
      await page.reload();

      // Re-authenticate if needed after reload
      const authMe = await page.request.get("/auth/me");
      if (authMe.ok()) {
        const me = (await authMe.json()) as { authenticated: boolean };
        if (!me.authenticated) {
          await ensureAuthenticated(page);
          await page.goto("/");
        }
      }

      // Wait for the writer window to reappear after reload
      await expect
        .poll(
          async () => {
            if (await isVisible(writerWindowTitle)) return "writer";
            return "pending";
          },
          { timeout: 60_000, intervals: [1000, 2000] }
        )
        .toBe("writer");

      // Wait for document to finish loading after reload too
      await expect
        .poll(
          async () => {
            const bodyVisible = await isVisible(writerBody);
            const bodyText = bodyVisible
              ? ((await writerBody.textContent()) ?? "")
              : "";
            if (bodyText.length > 10) return "ready";
            return "loading";
          },
          { timeout: 60_000, intervals: [2000, 3000] }
        )
        .toBe("ready");

      // Verify the document still has content (not a NOT_FOUND error)
      const bodyTextAfterReload = (await writerBody.textContent()) ?? "";
      expect(bodyTextAfterReload.length).toBeGreaterThan(0);

      // Still no raw research text after reload
      expect(bodyTextAfterReload).not.toContain("Research pulse for");
      expect(bodyTextAfterReload).not.toContain("Fetched source:");

      await page.screenshot({
        path: "../artifacts/playwright/writer-bugfix-after-reload.png",
        fullPage: true,
      });
    }
  });
});
