creation_rules:
  - path_regex: ^infra/secrets/.*\.sops\.ya?ml$
    key_groups:
      - age:
          - age1rc8spu6fchqcewtdkv43xjxspqgu409rxmsm8vp7mjlx88gg9ghqalgas7
          - age196tf78czmp6d2qedla8lhuv04esvpfk6xntf8s0ta5rthne9cq5qxw3xlc
