// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated class types.

use baml::{BamlEncode, BamlDecode};
use super::*;




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct AgentPlan {



    pub thinking: String,



    pub tool_calls: Vec<AgentToolCall>,



    pub final_response: Option<String>,



    pub confidence: f64,


}



impl AsRef<AgentPlan> for AgentPlan {
    fn as_ref(&self) -> &AgentPlan {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct AgentToolCall {



    pub tool_name: String,



    pub tool_args: String,



    pub reasoning: String,


}



impl AsRef<AgentToolCall> for AgentToolCall {
    fn as_ref(&self) -> &AgentToolCall {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct Message {



    pub role: String,



    pub content: String,


}



impl AsRef<Message> for Message {
    fn as_ref(&self) -> &Message {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct Resume {



    pub name: String,



    pub email: String,



    pub experience: Vec<String>,



    pub skills: Vec<String>,


}



impl AsRef<Resume> for Resume {
    fn as_ref(&self) -> &Resume {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct StreamChunk {



    pub chunk_type: String,



    pub content: String,


}



impl AsRef<StreamChunk> for StreamChunk {
    fn as_ref(&self) -> &StreamChunk {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode)]

pub struct ToolResult {



    pub tool_name: String,



    pub success: bool,



    pub output: String,



    pub error: Option<String>,


}



impl AsRef<ToolResult> for ToolResult {
    fn as_ref(&self) -> &ToolResult {
        self
    }
}

