// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod unions;
mod type_aliases;

pub use classes::*;
pub use enums::*;
pub use unions::*;
pub use type_aliases::*;

// Re-export types from baml runtime
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone)]
pub enum Types {

    AgentPlan(AgentPlan),

    AgentToolCall(AgentToolCall),

    Message(Message),

    Resume(Resume),

    StreamChunk(StreamChunk),

    ToolResult(ToolResult),



}

impl baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            Types::AgentPlan(_) => "AgentPlan",

            Types::AgentToolCall(_) => "AgentToolCall",

            Types::Message(_) => "Message",

            Types::Resume(_) => "Resume",

            Types::StreamChunk(_) => "StreamChunk",

            Types::ToolResult(_) => "ToolResult",




        }
    }
}