#!/bin/bash
set -euo pipefail

# Btrfs reformat script for OVH nodes (run from rescue mode)
# Converts md127 (root) from ext4 to btrfs with @ and @data subvolumes
# Boot partition (md126) is left untouched
#
# Usage: ssh into rescue mode, then run this script

echo "=== ChoirOS btrfs reformat ==="
echo "This will DESTROY the ext4 root filesystem on md127"
echo "Boot partition (md126) will NOT be touched"
echo ""

# Step 1: Assemble RAID arrays
echo "==> Assembling RAID arrays..."
mdadm --assemble --scan 2>/dev/null || true
sleep 2

# Verify arrays
echo "==> RAID status:"
cat /proc/mdstat
echo ""

# Find the root array (the large one)
ROOT_DEV=""
for md in /dev/md*; do
    [ -b "$md" ] || continue
    size=$(blockdev --getsize64 "$md" 2>/dev/null || echo 0)
    # Root array is > 100GB
    if [ "$size" -gt 107374182400 ]; then
        ROOT_DEV="$md"
        break
    fi
done

if [ -z "$ROOT_DEV" ]; then
    echo "ERROR: Could not find root md array (>100GB)"
    echo "Available block devices:"
    lsblk
    exit 1
fi

echo "==> Root device: $ROOT_DEV ($(blockdev --getsize64 "$ROOT_DEV" | numfmt --to=iec))"

# Step 2: Mount old filesystem and back up
echo ""
echo "==> Mounting old filesystem for backup..."
mkdir -p /mnt/old
mount "$ROOT_DEV" /mnt/old

echo "==> Current data usage:"
du -sh /mnt/old/ --exclude=/mnt/old/nix 2>/dev/null || true
du -sh /mnt/old/nix/store 2>/dev/null || true

echo ""
echo "==> Backing up to /tmp/backup..."
mkdir -p /tmp/backup
rsync -aAX --info=progress2 \
    --exclude='/dev/*' \
    --exclude='/proc/*' \
    --exclude='/sys/*' \
    --exclude='/tmp/*' \
    --exclude='/run/*' \
    --exclude='/mnt/*' \
    --exclude='/lost+found' \
    /mnt/old/ /tmp/backup/

echo "==> Backup complete: $(du -sh /tmp/backup | cut -f1)"
umount /mnt/old

# Step 3: Format as btrfs
echo ""
echo "==> Formatting $ROOT_DEV as btrfs..."
mkfs.btrfs -f -L choiros "$ROOT_DEV"

# Step 4: Create subvolumes
echo "==> Creating subvolumes..."
mount "$ROOT_DEV" /mnt/old
btrfs subvolume create /mnt/old/@
btrfs subvolume create /mnt/old/@data

# Create per-user storage directories in @data
mkdir -p /mnt/old/@data/users
mkdir -p /mnt/old/@data/snapshots

echo "==> Subvolume layout:"
btrfs subvolume list /mnt/old
umount /mnt/old

# Step 5: Mount @ subvolume and restore
echo ""
echo "==> Mounting @ subvolume and restoring backup..."
mount -o subvol=@,compress=zstd,noatime "$ROOT_DEV" /mnt/old
rsync -aAX --info=progress2 /tmp/backup/ /mnt/old/

# Create /data mountpoint
mkdir -p /mnt/old/data

echo "==> Restore complete"

# Step 6: Update fstab
echo ""
echo "==> Updating fstab..."
BTRFS_UUID=$(blkid -s UUID -o value "$ROOT_DEV")
cat > /mnt/old/etc/fstab << FSTAB
# Generated by btrfs-reformat.sh
# btrfs root with subvolumes
$ROOT_DEV / btrfs subvol=@,compress=zstd,noatime 0 0
$ROOT_DEV /data btrfs subvol=@data,compress=zstd,noatime 0 0
/dev/md/boot /boot ext4 defaults 0 2
/dev/disk/by-partlabel/disk-nvme0-ESP /boot/efi vfat umask=0077 0 2
FSTAB

echo "==> New fstab:"
cat /mnt/old/etc/fstab

# Step 7: Verify GRUB can find the kernel
echo ""
echo "==> Checking boot partition..."
mkdir -p /mnt/old/boot
mount /dev/md126 /mnt/old/boot 2>/dev/null || mount /dev/md/boot /mnt/old/boot 2>/dev/null || true
if [ -d /mnt/old/boot/kernels ]; then
    echo "==> Boot kernels present:"
    ls /mnt/old/boot/kernels/ | head -5
else
    echo "WARNING: No kernels found in /boot/kernels/"
fi

# Verify initrd exists
echo "==> Checking for btrfs in initrd..."
if ls /mnt/old/boot/kernels/*-initrd 2>/dev/null | head -1 | xargs -I{} file {} | grep -q "gzip\|cpio"; then
    echo "==> Initrd found (btrfs support was pre-installed via nixos-rebuild boot)"
fi

umount /mnt/old/boot 2>/dev/null || true
umount /mnt/old

echo ""
echo "=== Reformat complete ==="
echo "Filesystem: btrfs on $ROOT_DEV (UUID: $BTRFS_UUID)"
echo "Subvolumes: @ (root), @data (per-user storage)"
echo ""
echo "Next steps:"
echo "  1. Set boot back to normal: python3 scripts/ops/ovh-api.py normal b"
echo "  2. Or reboot from rescue: reboot"
echo "  3. Verify: ssh root@<ip> 'mount | grep btrfs && btrfs subvolume list /'"
