// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated TypeBuilder wrappers for type-safe schema access.

mod classes;
mod enums;

pub use classes::*;
pub use enums::*;

use std::sync::Arc;

/// TypeBuilder for dynamic type construction.
///
/// This wrapper provides access to the BAML TypeBuilder for creating
/// dynamic types at runtime. Use `TypeBuilder::new()` to create an instance.
///
/// Access schema-defined classes and enums via methods:
/// - `tb.ClassName()` returns the class builder
/// - `tb.EnumName()` returns the enum builder
#[derive(Clone)]
pub struct TypeBuilder {
    inner: Arc<baml::TypeBuilder>,
}

impl TypeBuilder {
    /// Create a new TypeBuilder for dynamic type construction.
    ///
    /// # Example
    /// ```ignore
    /// let tb = TypeBuilder::new();
    /// let my_enum = tb.add_enum("MyDynamicEnum")?;
    /// my_enum.add_value("Option1")?;
    /// ```
    pub fn new() -> Self {
        Self {
            inner: Arc::new(super::runtime::get_runtime().new_type_builder()),
        }
    }

    /// Get reference to inner TypeBuilder for FFI calls.
    pub(crate) fn inner(&self) -> &baml::TypeBuilder {
        &self.inner
    }

    // =========================================================================
    // Schema Class Accessors (1:1 with schema class names)
    // =========================================================================

    /// Access the `AgentPlan` class builder.
    pub fn AgentPlan(&self) -> AgentPlanClassBuilder {
        AgentPlanClassBuilder::new(
            self.inner
                .get_class("AgentPlan")
                .expect("class AgentPlan is defined in schema"),
        )
    }

    /// Access the `AgentToolArgs` class builder.
    pub fn AgentToolArgs(&self) -> AgentToolArgsClassBuilder {
        AgentToolArgsClassBuilder::new(
            self.inner
                .get_class("AgentToolArgs")
                .expect("class AgentToolArgs is defined in schema"),
        )
    }

    /// Access the `AgentToolCall` class builder.
    pub fn AgentToolCall(&self) -> AgentToolCallClassBuilder {
        AgentToolCallClassBuilder::new(
            self.inner
                .get_class("AgentToolCall")
                .expect("class AgentToolCall is defined in schema"),
        )
    }

    /// Access the `BashToolArgs` class builder.
    pub fn BashToolArgs(&self) -> BashToolArgsClassBuilder {
        BashToolArgsClassBuilder::new(
            self.inner
                .get_class("BashToolArgs")
                .expect("class BashToolArgs is defined in schema"),
        )
    }

    /// Access the `ListFilesToolArgs` class builder.
    pub fn ListFilesToolArgs(&self) -> ListFilesToolArgsClassBuilder {
        ListFilesToolArgsClassBuilder::new(
            self.inner
                .get_class("ListFilesToolArgs")
                .expect("class ListFilesToolArgs is defined in schema"),
        )
    }

    /// Access the `Message` class builder.
    pub fn Message(&self) -> MessageClassBuilder {
        MessageClassBuilder::new(
            self.inner
                .get_class("Message")
                .expect("class Message is defined in schema"),
        )
    }

    /// Access the `ReadFileToolArgs` class builder.
    pub fn ReadFileToolArgs(&self) -> ReadFileToolArgsClassBuilder {
        ReadFileToolArgsClassBuilder::new(
            self.inner
                .get_class("ReadFileToolArgs")
                .expect("class ReadFileToolArgs is defined in schema"),
        )
    }

    /// Access the `Resume` class builder.
    pub fn Resume(&self) -> ResumeClassBuilder {
        ResumeClassBuilder::new(
            self.inner
                .get_class("Resume")
                .expect("class Resume is defined in schema"),
        )
    }

    /// Access the `SearchFilesToolArgs` class builder.
    pub fn SearchFilesToolArgs(&self) -> SearchFilesToolArgsClassBuilder {
        SearchFilesToolArgsClassBuilder::new(
            self.inner
                .get_class("SearchFilesToolArgs")
                .expect("class SearchFilesToolArgs is defined in schema"),
        )
    }

    /// Access the `StreamChunk` class builder.
    pub fn StreamChunk(&self) -> StreamChunkClassBuilder {
        StreamChunkClassBuilder::new(
            self.inner
                .get_class("StreamChunk")
                .expect("class StreamChunk is defined in schema"),
        )
    }

    /// Access the `ToolResult` class builder.
    pub fn ToolResult(&self) -> ToolResultClassBuilder {
        ToolResultClassBuilder::new(
            self.inner
                .get_class("ToolResult")
                .expect("class ToolResult is defined in schema"),
        )
    }

    /// Access the `WriteFileToolArgs` class builder.
    pub fn WriteFileToolArgs(&self) -> WriteFileToolArgsClassBuilder {
        WriteFileToolArgsClassBuilder::new(
            self.inner
                .get_class("WriteFileToolArgs")
                .expect("class WriteFileToolArgs is defined in schema"),
        )
    }

    // =========================================================================
    // Schema Enum Accessors (1:1 with schema enum names)
    // =========================================================================

    // =========================================================================
    // Primitive Types (all infallible)
    // =========================================================================

    /// Get the string type.
    pub fn string(&self) -> baml::TypeDef {
        self.inner.string()
    }

    /// Get the int type.
    pub fn int(&self) -> baml::TypeDef {
        self.inner.int()
    }

    /// Get the float type.
    pub fn float(&self) -> baml::TypeDef {
        self.inner.float()
    }

    /// Get the bool type.
    pub fn bool(&self) -> baml::TypeDef {
        self.inner.bool()
    }

    /// Get the null type.
    pub fn null(&self) -> baml::TypeDef {
        self.inner.null()
    }

    // =========================================================================
    // Literal Types (all infallible)
    // =========================================================================

    /// Create a literal string type.
    pub fn literal_string(&self, value: &str) -> baml::TypeDef {
        self.inner.literal_string(value)
    }

    /// Create a literal int type.
    pub fn literal_int(&self, value: i64) -> baml::TypeDef {
        self.inner.literal_int(value)
    }

    /// Create a literal bool type.
    pub fn literal_bool(&self, value: bool) -> baml::TypeDef {
        self.inner.literal_bool(value)
    }

    // =========================================================================
    // Composite Types (all infallible)
    // =========================================================================

    /// Create a list type.
    pub fn list(&self, inner: &baml::TypeDef) -> baml::TypeDef {
        self.inner.list(inner)
    }

    /// Create an optional type.
    pub fn optional(&self, inner: &baml::TypeDef) -> baml::TypeDef {
        self.inner.optional(inner)
    }

    /// Create a map type.
    pub fn map(&self, key: &baml::TypeDef, value: &baml::TypeDef) -> baml::TypeDef {
        self.inner.map(key, value)
    }

    /// Create a union type.
    pub fn union(&self, types: &[&baml::TypeDef]) -> baml::TypeDef {
        self.inner.union(types)
    }

    // =========================================================================
    // Schema Operations (fallible)
    // =========================================================================

    /// Add BAML schema definitions.
    pub fn add_baml(&self, baml_source: &str) -> Result<(), baml::BamlError> {
        self.inner.add_baml(baml_source)
    }

    /// Print the TypeBuilder state for debugging.
    pub fn print(&self) -> String {
        self.inner.print()
    }

    // =========================================================================
    // Dynamic Enum Operations
    // =========================================================================

    /// Add a new dynamic enum.
    pub fn add_enum(&self, name: &str) -> Result<baml::EnumBuilder, baml::BamlError> {
        self.inner.add_enum(name)
    }

    /// Get an enum by name (returns None if not found).
    pub fn get_enum(&self, name: &str) -> Option<baml::EnumBuilder> {
        self.inner.get_enum(name)
    }

    /// List all enums.
    pub fn list_enums(&self) -> Vec<baml::EnumBuilder> {
        self.inner.list_enums()
    }

    // =========================================================================
    // Dynamic Class Operations
    // =========================================================================

    /// Add a new dynamic class.
    pub fn add_class(&self, name: &str) -> Result<baml::ClassBuilder, baml::BamlError> {
        self.inner.add_class(name)
    }

    /// Get a class by name (returns None if not found).
    pub fn get_class(&self, name: &str) -> Option<baml::ClassBuilder> {
        self.inner.get_class(name)
    }

    /// List all classes.
    pub fn list_classes(&self) -> Vec<baml::ClassBuilder> {
        self.inner.list_classes()
    }
}

impl Default for TypeBuilder {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Debug for TypeBuilder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TypeBuilder")
            .field("state", &self.print())
            .finish()
    }
}
