// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated TypeBuilder wrappers for type-safe schema access.

#![allow(clippy::empty_line_after_doc_comments)]

mod classes;
mod enums;

pub use classes::{
    AgentDecisionClassBuilder, AgentToolArgsClassBuilder, AgentToolCallClassBuilder,
    BashToolArgsClassBuilder, ConductorBootstrapInputClassBuilder,
    ConductorBootstrapOutputClassBuilder, ConductorDecisionClassBuilder,
    ConductorDecisionInputClassBuilder, ConductorObjectiveRefineInputClassBuilder,
    ConductorObjectiveRefineOutputClassBuilder, ListFilesToolArgsClassBuilder, MessageClassBuilder,
    ReadFileToolArgsClassBuilder, ResearcherPlanInputClassBuilder,
    ResearcherPlanOutputClassBuilder, ResumeClassBuilder, SearchFilesToolArgsClassBuilder,
    StreamChunkClassBuilder, ToolResultClassBuilder, WebSearchToolArgsClassBuilder,
    WriteFileToolArgsClassBuilder,
};
pub use enums::{
    ActionEnumBuilder, ConductorActionEnumBuilder, ResearchActionEnumBuilder,
    ResearchStatusEnumBuilder,
};

use std::sync::Arc;

/// TypeBuilder for dynamic type construction.
///
/// This wrapper provides access to the BAML TypeBuilder for creating
/// dynamic types at runtime. Use `TypeBuilder::new()` to create an instance.
///
/// Access schema-defined classes and enums via methods:
/// - `tb.ClassName()` returns the class builder
/// - `tb.EnumName()` returns the enum builder
#[derive(Clone)]
pub struct TypeBuilder {
    inner: Arc<baml::TypeBuilder>,
}

impl TypeBuilder {
    /// Create a new TypeBuilder for dynamic type construction.
    ///
    /// # Example
    /// ```ignore
    /// let tb = TypeBuilder::new();
    /// let my_enum = tb.add_enum("MyDynamicEnum")?;
    /// my_enum.add_value("Option1")?;
    /// ```
    pub fn new() -> Self {
        Self {
            inner: Arc::new(super::runtime::get_runtime().new_type_builder()),
        }
    }

    /// Get reference to inner TypeBuilder for FFI calls.
    pub(crate) fn inner(&self) -> &baml::TypeBuilder {
        &self.inner
    }

    // =========================================================================
    // Schema Class Accessors (1:1 with schema class names)
    // =========================================================================

    /// Access the `AgentDecision` class builder.
    pub fn AgentDecision(&self) -> AgentDecisionClassBuilder {
        AgentDecisionClassBuilder::new(
            self.inner
                .get_class("AgentDecision")
                .expect("class AgentDecision is defined in schema"),
        )
    }

    /// Access the `AgentToolArgs` class builder.
    pub fn AgentToolArgs(&self) -> AgentToolArgsClassBuilder {
        AgentToolArgsClassBuilder::new(
            self.inner
                .get_class("AgentToolArgs")
                .expect("class AgentToolArgs is defined in schema"),
        )
    }

    /// Access the `AgentToolCall` class builder.
    pub fn AgentToolCall(&self) -> AgentToolCallClassBuilder {
        AgentToolCallClassBuilder::new(
            self.inner
                .get_class("AgentToolCall")
                .expect("class AgentToolCall is defined in schema"),
        )
    }

    /// Access the `BashToolArgs` class builder.
    pub fn BashToolArgs(&self) -> BashToolArgsClassBuilder {
        BashToolArgsClassBuilder::new(
            self.inner
                .get_class("BashToolArgs")
                .expect("class BashToolArgs is defined in schema"),
        )
    }

    /// Access the `ConductorBootstrapInput` class builder.
    pub fn ConductorBootstrapInput(&self) -> ConductorBootstrapInputClassBuilder {
        ConductorBootstrapInputClassBuilder::new(
            self.inner
                .get_class("ConductorBootstrapInput")
                .expect("class ConductorBootstrapInput is defined in schema"),
        )
    }

    /// Access the `ConductorBootstrapOutput` class builder.
    pub fn ConductorBootstrapOutput(&self) -> ConductorBootstrapOutputClassBuilder {
        ConductorBootstrapOutputClassBuilder::new(
            self.inner
                .get_class("ConductorBootstrapOutput")
                .expect("class ConductorBootstrapOutput is defined in schema"),
        )
    }

    /// Access the `ConductorDecision` class builder.
    pub fn ConductorDecision(&self) -> ConductorDecisionClassBuilder {
        ConductorDecisionClassBuilder::new(
            self.inner
                .get_class("ConductorDecision")
                .expect("class ConductorDecision is defined in schema"),
        )
    }

    /// Access the `ConductorDecisionInput` class builder.
    pub fn ConductorDecisionInput(&self) -> ConductorDecisionInputClassBuilder {
        ConductorDecisionInputClassBuilder::new(
            self.inner
                .get_class("ConductorDecisionInput")
                .expect("class ConductorDecisionInput is defined in schema"),
        )
    }

    /// Access the `ConductorObjectiveRefineInput` class builder.
    pub fn ConductorObjectiveRefineInput(&self) -> ConductorObjectiveRefineInputClassBuilder {
        ConductorObjectiveRefineInputClassBuilder::new(
            self.inner
                .get_class("ConductorObjectiveRefineInput")
                .expect("class ConductorObjectiveRefineInput is defined in schema"),
        )
    }

    /// Access the `ConductorObjectiveRefineOutput` class builder.
    pub fn ConductorObjectiveRefineOutput(&self) -> ConductorObjectiveRefineOutputClassBuilder {
        ConductorObjectiveRefineOutputClassBuilder::new(
            self.inner
                .get_class("ConductorObjectiveRefineOutput")
                .expect("class ConductorObjectiveRefineOutput is defined in schema"),
        )
    }

    /// Access the `ListFilesToolArgs` class builder.
    pub fn ListFilesToolArgs(&self) -> ListFilesToolArgsClassBuilder {
        ListFilesToolArgsClassBuilder::new(
            self.inner
                .get_class("ListFilesToolArgs")
                .expect("class ListFilesToolArgs is defined in schema"),
        )
    }

    /// Access the `Message` class builder.
    pub fn Message(&self) -> MessageClassBuilder {
        MessageClassBuilder::new(
            self.inner
                .get_class("Message")
                .expect("class Message is defined in schema"),
        )
    }

    /// Access the `ReadFileToolArgs` class builder.
    pub fn ReadFileToolArgs(&self) -> ReadFileToolArgsClassBuilder {
        ReadFileToolArgsClassBuilder::new(
            self.inner
                .get_class("ReadFileToolArgs")
                .expect("class ReadFileToolArgs is defined in schema"),
        )
    }

    /// Access the `ResearcherPlanInput` class builder.
    pub fn ResearcherPlanInput(&self) -> ResearcherPlanInputClassBuilder {
        ResearcherPlanInputClassBuilder::new(
            self.inner
                .get_class("ResearcherPlanInput")
                .expect("class ResearcherPlanInput is defined in schema"),
        )
    }

    /// Access the `ResearcherPlanOutput` class builder.
    pub fn ResearcherPlanOutput(&self) -> ResearcherPlanOutputClassBuilder {
        ResearcherPlanOutputClassBuilder::new(
            self.inner
                .get_class("ResearcherPlanOutput")
                .expect("class ResearcherPlanOutput is defined in schema"),
        )
    }

    /// Access the `Resume` class builder.
    pub fn Resume(&self) -> ResumeClassBuilder {
        ResumeClassBuilder::new(
            self.inner
                .get_class("Resume")
                .expect("class Resume is defined in schema"),
        )
    }

    /// Access the `SearchFilesToolArgs` class builder.
    pub fn SearchFilesToolArgs(&self) -> SearchFilesToolArgsClassBuilder {
        SearchFilesToolArgsClassBuilder::new(
            self.inner
                .get_class("SearchFilesToolArgs")
                .expect("class SearchFilesToolArgs is defined in schema"),
        )
    }

    /// Access the `StreamChunk` class builder.
    pub fn StreamChunk(&self) -> StreamChunkClassBuilder {
        StreamChunkClassBuilder::new(
            self.inner
                .get_class("StreamChunk")
                .expect("class StreamChunk is defined in schema"),
        )
    }

    /// Access the `ToolResult` class builder.
    pub fn ToolResult(&self) -> ToolResultClassBuilder {
        ToolResultClassBuilder::new(
            self.inner
                .get_class("ToolResult")
                .expect("class ToolResult is defined in schema"),
        )
    }

    /// Access the `WebSearchToolArgs` class builder.
    pub fn WebSearchToolArgs(&self) -> WebSearchToolArgsClassBuilder {
        WebSearchToolArgsClassBuilder::new(
            self.inner
                .get_class("WebSearchToolArgs")
                .expect("class WebSearchToolArgs is defined in schema"),
        )
    }

    /// Access the `WriteFileToolArgs` class builder.
    pub fn WriteFileToolArgs(&self) -> WriteFileToolArgsClassBuilder {
        WriteFileToolArgsClassBuilder::new(
            self.inner
                .get_class("WriteFileToolArgs")
                .expect("class WriteFileToolArgs is defined in schema"),
        )
    }

    // =========================================================================
    // Schema Enum Accessors (1:1 with schema enum names)
    // =========================================================================

    /// Access the `Action` enum builder.
    pub fn Action(&self) -> ActionEnumBuilder {
        ActionEnumBuilder::new(
            self.inner
                .get_enum("Action")
                .expect("enum Action is defined in schema"),
        )
    }

    /// Access the `ConductorAction` enum builder.
    pub fn ConductorAction(&self) -> ConductorActionEnumBuilder {
        ConductorActionEnumBuilder::new(
            self.inner
                .get_enum("ConductorAction")
                .expect("enum ConductorAction is defined in schema"),
        )
    }

    /// Access the `ResearchAction` enum builder.
    pub fn ResearchAction(&self) -> ResearchActionEnumBuilder {
        ResearchActionEnumBuilder::new(
            self.inner
                .get_enum("ResearchAction")
                .expect("enum ResearchAction is defined in schema"),
        )
    }

    /// Access the `ResearchStatus` enum builder.
    pub fn ResearchStatus(&self) -> ResearchStatusEnumBuilder {
        ResearchStatusEnumBuilder::new(
            self.inner
                .get_enum("ResearchStatus")
                .expect("enum ResearchStatus is defined in schema"),
        )
    }

    // =========================================================================
    // Primitive Types (all infallible)
    // =========================================================================

    /// Get the string type.
    pub fn string(&self) -> baml::TypeDef {
        self.inner.string()
    }

    /// Get the int type.
    pub fn int(&self) -> baml::TypeDef {
        self.inner.int()
    }

    /// Get the float type.
    pub fn float(&self) -> baml::TypeDef {
        self.inner.float()
    }

    /// Get the bool type.
    pub fn bool(&self) -> baml::TypeDef {
        self.inner.bool()
    }

    /// Get the null type.
    pub fn null(&self) -> baml::TypeDef {
        self.inner.null()
    }

    // =========================================================================
    // Literal Types (all infallible)
    // =========================================================================

    /// Create a literal string type.
    pub fn literal_string(&self, value: &str) -> baml::TypeDef {
        self.inner.literal_string(value)
    }

    /// Create a literal int type.
    pub fn literal_int(&self, value: i64) -> baml::TypeDef {
        self.inner.literal_int(value)
    }

    /// Create a literal bool type.
    pub fn literal_bool(&self, value: bool) -> baml::TypeDef {
        self.inner.literal_bool(value)
    }

    // =========================================================================
    // Composite Types (all infallible)
    // =========================================================================

    /// Create a list type.
    pub fn list(&self, inner: &baml::TypeDef) -> baml::TypeDef {
        self.inner.list(inner)
    }

    /// Create an optional type.
    pub fn optional(&self, inner: &baml::TypeDef) -> baml::TypeDef {
        self.inner.optional(inner)
    }

    /// Create a map type.
    pub fn map(&self, key: &baml::TypeDef, value: &baml::TypeDef) -> baml::TypeDef {
        self.inner.map(key, value)
    }

    /// Create a union type.
    pub fn union(&self, types: &[&baml::TypeDef]) -> baml::TypeDef {
        self.inner.union(types)
    }

    // =========================================================================
    // Schema Operations (fallible)
    // =========================================================================

    /// Add BAML schema definitions.
    pub fn add_baml(&self, baml_source: &str) -> Result<(), baml::BamlError> {
        self.inner.add_baml(baml_source)
    }

    /// Print the TypeBuilder state for debugging.
    pub fn print(&self) -> String {
        self.inner.print()
    }

    // =========================================================================
    // Dynamic Enum Operations
    // =========================================================================

    /// Add a new dynamic enum.
    pub fn add_enum(&self, name: &str) -> Result<baml::EnumBuilder, baml::BamlError> {
        self.inner.add_enum(name)
    }

    /// Get an enum by name (returns None if not found).
    pub fn get_enum(&self, name: &str) -> Option<baml::EnumBuilder> {
        self.inner.get_enum(name)
    }

    /// List all enums.
    pub fn list_enums(&self) -> Vec<baml::EnumBuilder> {
        self.inner.list_enums()
    }

    // =========================================================================
    // Dynamic Class Operations
    // =========================================================================

    /// Add a new dynamic class.
    pub fn add_class(&self, name: &str) -> Result<baml::ClassBuilder, baml::BamlError> {
        self.inner.add_class(name)
    }

    /// Get a class by name (returns None if not found).
    pub fn get_class(&self, name: &str) -> Option<baml::ClassBuilder> {
        self.inner.get_class(name)
    }

    /// List all classes.
    pub fn list_classes(&self) -> Vec<baml::ClassBuilder> {
        self.inner.list_classes()
    }
}

impl Default for TypeBuilder {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Debug for TypeBuilder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TypeBuilder")
            .field("state", &self.print())
            .finish()
    }
}
