// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for actors
 */
export type ActorId = string;

/**
 * App definition for dynamic app registration
 */
export type AppDefinition = { id: string, name: string, icon: string, component_code: string, default_width: number, default_height: number, };

/**
 * Request to append an event
 */
export type AppendEvent = { event_type: string, payload: unknown, actor_id: ActorId, user_id: string, };

/**
 * Chat message for UI display
 */
export type ChatMessage = { id: string, text: string, sender: Sender, timestamp: string, pending: boolean, };

/**
 * Messages that can be sent to ChatActor
 */
export type ChatMsg = { "UserTyped": { text: string, window_id: string, } } | { "AssistantReply": { text: string, model: string, } } | { "ToolCall": { tool: string, args: unknown, call_id: string, } } | { "ToolResult": { call_id: string, status: ToolStatus, output: unknown, } };

/**
 * Desktop state - all windows and their positions
 */
export type DesktopState = { windows: Array<WindowState>, active_window: string | null, apps: Array<AppDefinition>, };

/**
 * Event - append-only log entry
 * All state changes are logged as events
 */
export type Event = { 
/**
 * Global sequence number (strictly increasing)
 */
seq: bigint, 
/**
 * Unique event ID (ULID)
 */
event_id: string, 
/**
 * When the event occurred
 */
timestamp: string, 
/**
 * Which actor produced this event
 */
actor_id: ActorId, 
/**
 * Event type (e.g., "chat.user_msg", "file.write")
 */
event_type: string, 
/**
 * Event-specific payload
 */
payload: unknown, 
/**
 * Which user triggered this (for audit)
 */
user_id: string, };

/**
 * Query events for an actor
 */
export type QueryEvents = { actor_id: ActorId, since_seq: bigint, };

export type Sender = "User" | "Assistant" | "System";

/**
 * Tool call from LLM
 */
export type ToolCall = { id: string, tool: string, args: unknown, };

/**
 * Tool definition for LLM
 */
export type ToolDef = { name: string, description: string, parameters: unknown, };

export type ToolStatus = "Success" | { "Error": string };

export type ViewerCapabilities = { readonly: boolean, };

export type ViewerDescriptor = { kind: ViewerKind, resource: ViewerResource, capabilities: ViewerCapabilities, };

export type ViewerKind = "text" | "image";

export type ViewerResource = { uri: string, mime: string, };

export type ViewerRevision = { rev: bigint, updated_at: string, };

/**
 * Individual window state
 */
export type WindowState = { id: string, app_id: string, title: string, x: number, y: number, width: number, height: number, z_index: number, minimized: boolean, maximized: boolean, props: unknown, };

/**
 * WebSocket message protocol
 */
export type WsMsg = { "type": "Subscribe", actor_id: ActorId, } | { "type": "Send", actor_id: ActorId, payload: unknown, } | { "type": "Event", actor_id: ActorId, event: Event, } | { "type": "State", actor_id: ActorId, state: unknown, } | { "type": "Error", message: string, };
