// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for actors
 */
export type ActorId = string;

/**
 * App definition for dynamic app registration
 */
export type AppDefinition = { id: string, name: string, icon: string, component_code: string, default_width: number, default_height: number, };

/**
 * Request to append an event
 */
export type AppendEvent = { event_type: string, payload: unknown, actor_id: ActorId, user_id: string, };

/**
 * Chat message for UI display
 */
export type ChatMessage = { id: string, text: string, sender: Sender, timestamp: string, pending: boolean, };

/**
 * Messages that can be sent to ChatActor
 */
export type ChatMsg = { "UserTyped": { text: string, window_id: string, } } | { "AssistantReply": { text: string, model: string, } } | { "ToolCall": { tool: string, args: unknown, call_id: string, } } | { "ToolResult": { call_id: string, status: ToolStatus, output: unknown, } };

/**
 * Desktop state - all windows and their positions
 */
export type DesktopState = { windows: Array<WindowState>, active_window: string | null, apps: Array<AppDefinition>, };

/**
 * Event - append-only log entry
 * All state changes are logged as events
 */
export type Event = { 
/**
 * Global sequence number (strictly increasing)
 */
seq: bigint, 
/**
 * Unique event ID (ULID)
 */
event_id: string, 
/**
 * When the event occurred
 */
timestamp: string, 
/**
 * Which actor produced this event
 */
actor_id: ActorId, 
/**
 * Event type (e.g., "chat.user_msg", "file.write")
 */
event_type: string, 
/**
 * Event-specific payload
 */
payload: unknown, 
/**
 * Which user triggered this (for audit)
 */
user_id: string, };

/**
 * Query events for an actor
 */
export type QueryEvents = { actor_id: ActorId, since_seq: bigint, };

export type Sender = "User" | "Assistant" | "System";

/**
 * Tool call from LLM
 */
export type ToolCall = { id: string, tool: string, args: unknown, };

/**
 * Tool definition for LLM
 */
export type ToolDef = { name: string, description: string, parameters: unknown, };

export type ToolStatus = "Success" | { "Error": string };

export type ViewerCapabilities = { readonly: boolean, };

export type ViewerDescriptor = { kind: ViewerKind, resource: ViewerResource, capabilities: ViewerCapabilities, };

export type ViewerKind = "text" | "image";

export type ViewerResource = { uri: string, mime: string, };

export type ViewerRevision = { rev: bigint, updated_at: string, };

/**
 * Individual window state
 */
export type WindowState = { id: string, app_id: string, title: string, x: number, y: number, width: number, height: number, z_index: number, minimized: boolean, maximized: boolean, props: unknown, };

export type WorkerArtifact = { artifact_id: string, kind: string, reference: string, };

export type WorkerEscalation = { escalation_id: string, kind: WorkerEscalationKind, reason: string, urgency: WorkerEscalationUrgency, options: Array<string>, recommended_option: string | null, requires_human: boolean | null, };

export type WorkerEscalationKind = "blocker" | "help" | "approval" | "conflict";

export type WorkerEscalationUrgency = "low" | "medium" | "high";

export type WorkerFinding = { finding_id: string, claim: string, confidence: number, evidence_refs: Array<string>, novel: boolean | null, };

export type WorkerLearning = { learning_id: string, insight: string, confidence: number, supports: Array<string>, changes_plan: boolean | null, };

export type WorkerSignalRejectReason = "max_per_turn_exceeded" | "low_confidence" | "missing_evidence" | "duplicate_within_window" | "escalation_cooldown" | "invalid_payload";

export type WorkerSignalRejection = { signal_type: WorkerSignalType, signal_id: string, reason: WorkerSignalRejectReason, detail: string, };

export type WorkerSignalType = "finding" | "learning" | "escalation" | "artifact";

export type WorkerTurnReport = { turn_id: string, worker_id: string, task_id: string, worker_role: string | null, status: WorkerTurnStatus, summary: string | null, findings: Array<WorkerFinding>, learnings: Array<WorkerLearning>, escalations: Array<WorkerEscalation>, artifacts: Array<WorkerArtifact>, created_at: string | null, };

export type WorkerTurnReportIngestResult = { accepted_findings: number, accepted_learnings: number, accepted_escalations: number, accepted_artifacts: number, escalation_notified: boolean, rejections: Array<WorkerSignalRejection>, };

export type WorkerTurnStatus = "running" | "completed" | "failed" | "blocked";

/**
 * WebSocket message protocol
 */
export type WsMsg = { "type": "Subscribe", actor_id: ActorId, } | { "type": "Send", actor_id: ActorId, payload: unknown, } | { "type": "Event", actor_id: ActorId, event: Event, } | { "type": "State", actor_id: ActorId, state: unknown, } | { "type": "Error", message: string, };
