# Hardware configuration for OVH SYS-1 bare metal (shared between Node A & B)
# 2x NVMe RAID1, btrfs root with @ and @data subvolumes, UEFI
#
# This replaces the disko config — uses stable UUIDs from the actual disks.
# Each node's hardware-configuration.nix (generated by nixos-generate-config)
# provides the UUIDs. This module provides the common hardware settings.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "nvme"
    "sd_mod"
    "xhci_pci"
    "usb_storage"
    "usbhid"
    "raid1"
    "md_mod"
    "btrfs"
  ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.swraid.enable = true;
  boot.swraid.mdadmConf = "MAILADDR root";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
