// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod type_aliases;
mod unions;

pub use classes::{
    AgentDecision, AgentToolArgs, AgentToolCall, BashToolArgs, ConductorBootstrapInput,
    ConductorBootstrapOutput, ConductorDecision, ConductorDecisionInput,
    ConductorObjectiveRefineInput, ConductorObjectiveRefineOutput, ListFilesToolArgs, Message,
    ReadFileToolArgs, ResearcherPlanInput, ResearcherPlanOutput, Resume, SearchFilesToolArgs,
    StreamChunk, ToolResult, WebSearchToolArgs, WriteFileToolArgs,
};
pub use type_aliases::*;
pub use unions::*;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone)]
pub enum StreamTypes {
    AgentDecision(AgentDecision),

    AgentToolArgs(AgentToolArgs),

    AgentToolCall(AgentToolCall),

    BashToolArgs(BashToolArgs),

    ConductorBootstrapInput(ConductorBootstrapInput),

    ConductorBootstrapOutput(ConductorBootstrapOutput),

    ConductorDecision(ConductorDecision),

    ConductorDecisionInput(ConductorDecisionInput),

    ConductorObjectiveRefineInput(ConductorObjectiveRefineInput),

    ConductorObjectiveRefineOutput(ConductorObjectiveRefineOutput),

    ListFilesToolArgs(ListFilesToolArgs),

    Message(Message),

    ReadFileToolArgs(ReadFileToolArgs),

    ResearcherPlanInput(ResearcherPlanInput),

    ResearcherPlanOutput(ResearcherPlanOutput),

    Resume(Resume),

    SearchFilesToolArgs(SearchFilesToolArgs),

    StreamChunk(StreamChunk),

    ToolResult(ToolResult),

    WebSearchToolArgs(WebSearchToolArgs),

    WriteFileToolArgs(WriteFileToolArgs),
}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            StreamTypes::AgentDecision(_) => "AgentDecision",

            StreamTypes::AgentToolArgs(_) => "AgentToolArgs",

            StreamTypes::AgentToolCall(_) => "AgentToolCall",

            StreamTypes::BashToolArgs(_) => "BashToolArgs",

            StreamTypes::ConductorBootstrapInput(_) => "ConductorBootstrapInput",

            StreamTypes::ConductorBootstrapOutput(_) => "ConductorBootstrapOutput",

            StreamTypes::ConductorDecision(_) => "ConductorDecision",

            StreamTypes::ConductorDecisionInput(_) => "ConductorDecisionInput",

            StreamTypes::ConductorObjectiveRefineInput(_) => "ConductorObjectiveRefineInput",

            StreamTypes::ConductorObjectiveRefineOutput(_) => "ConductorObjectiveRefineOutput",

            StreamTypes::ListFilesToolArgs(_) => "ListFilesToolArgs",

            StreamTypes::Message(_) => "Message",

            StreamTypes::ReadFileToolArgs(_) => "ReadFileToolArgs",

            StreamTypes::ResearcherPlanInput(_) => "ResearcherPlanInput",

            StreamTypes::ResearcherPlanOutput(_) => "ResearcherPlanOutput",

            StreamTypes::Resume(_) => "Resume",

            StreamTypes::SearchFilesToolArgs(_) => "SearchFilesToolArgs",

            StreamTypes::StreamChunk(_) => "StreamChunk",

            StreamTypes::ToolResult(_) => "ToolResult",

            StreamTypes::WebSearchToolArgs(_) => "WebSearchToolArgs",

            StreamTypes::WriteFileToolArgs(_) => "WriteFileToolArgs",
        }
    }
}
