// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod type_aliases;
mod unions;

pub use classes::*;
pub use type_aliases::*;
pub use unions::*;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone)]
pub enum StreamTypes {
    AgentPlan(AgentPlan),

    AgentToolCall(AgentToolCall),

    Message(Message),

    Resume(Resume),

    StreamChunk(StreamChunk),

    ToolResult(ToolResult),
}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            StreamTypes::AgentPlan(_) => "AgentPlan",

            StreamTypes::AgentToolCall(_) => "AgentToolCall",

            StreamTypes::Message(_) => "Message",

            StreamTypes::Resume(_) => "Resume",

            StreamTypes::StreamChunk(_) => "StreamChunk",

            StreamTypes::ToolResult(_) => "ToolResult",
        }
    }
}
