// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod type_aliases;
mod unions;

pub use classes::*;
pub use type_aliases::*;
pub use unions::*;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone)]
pub enum StreamTypes {
    AgentDecision(AgentDecision),

    AgentToolArgs(AgentToolArgs),

    AgentToolCall(AgentToolCall),

    AlternativeAction(AlternativeAction),

    BashToolArgs(BashToolArgs),

    ConductorBootstrapInput(ConductorBootstrapInput),

    ConductorBootstrapOutput(ConductorBootstrapOutput),

    ConductorDecision(ConductorDecision),

    ConductorDecisionInput(ConductorDecisionInput),

    ConductorObjectiveRefineInput(ConductorObjectiveRefineInput),

    ConductorObjectiveRefineOutput(ConductorObjectiveRefineOutput),

    DetectedAnomaly(DetectedAnomaly),

    HistoricalResolution(HistoricalResolution),

    ListFilesToolArgs(ListFilesToolArgs),

    Message(Message),

    ReadFileToolArgs(ReadFileToolArgs),

    ResearcherPlanInput(ResearcherPlanInput),

    ResearcherPlanOutput(ResearcherPlanOutput),

    Resume(Resume),

    ReviewScope(ReviewScope),

    RiskItem(RiskItem),

    RunStateSnapshot(RunStateSnapshot),

    SearchFilesToolArgs(SearchFilesToolArgs),

    StreamChunk(StreamChunk),

    ToolResult(ToolResult),

    WatcherEscalation(WatcherEscalation),

    WatcherEvent(WatcherEvent),

    WatcherLogWindowInput(WatcherLogWindowInput),

    WatcherMitigationInput(WatcherMitigationInput),

    WatcherMitigationOutput(WatcherMitigationOutput),

    WatcherReviewOutput(WatcherReviewOutput),

    WebSearchToolArgs(WebSearchToolArgs),

    WriteFileToolArgs(WriteFileToolArgs),
}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            StreamTypes::AgentDecision(_) => "AgentDecision",

            StreamTypes::AgentToolArgs(_) => "AgentToolArgs",

            StreamTypes::AgentToolCall(_) => "AgentToolCall",

            StreamTypes::AlternativeAction(_) => "AlternativeAction",

            StreamTypes::BashToolArgs(_) => "BashToolArgs",

            StreamTypes::ConductorBootstrapInput(_) => "ConductorBootstrapInput",

            StreamTypes::ConductorBootstrapOutput(_) => "ConductorBootstrapOutput",

            StreamTypes::ConductorDecision(_) => "ConductorDecision",

            StreamTypes::ConductorDecisionInput(_) => "ConductorDecisionInput",

            StreamTypes::ConductorObjectiveRefineInput(_) => "ConductorObjectiveRefineInput",

            StreamTypes::ConductorObjectiveRefineOutput(_) => "ConductorObjectiveRefineOutput",

            StreamTypes::DetectedAnomaly(_) => "DetectedAnomaly",

            StreamTypes::HistoricalResolution(_) => "HistoricalResolution",

            StreamTypes::ListFilesToolArgs(_) => "ListFilesToolArgs",

            StreamTypes::Message(_) => "Message",

            StreamTypes::ReadFileToolArgs(_) => "ReadFileToolArgs",

            StreamTypes::ResearcherPlanInput(_) => "ResearcherPlanInput",

            StreamTypes::ResearcherPlanOutput(_) => "ResearcherPlanOutput",

            StreamTypes::Resume(_) => "Resume",

            StreamTypes::ReviewScope(_) => "ReviewScope",

            StreamTypes::RiskItem(_) => "RiskItem",

            StreamTypes::RunStateSnapshot(_) => "RunStateSnapshot",

            StreamTypes::SearchFilesToolArgs(_) => "SearchFilesToolArgs",

            StreamTypes::StreamChunk(_) => "StreamChunk",

            StreamTypes::ToolResult(_) => "ToolResult",

            StreamTypes::WatcherEscalation(_) => "WatcherEscalation",

            StreamTypes::WatcherEvent(_) => "WatcherEvent",

            StreamTypes::WatcherLogWindowInput(_) => "WatcherLogWindowInput",

            StreamTypes::WatcherMitigationInput(_) => "WatcherMitigationInput",

            StreamTypes::WatcherMitigationOutput(_) => "WatcherMitigationOutput",

            StreamTypes::WatcherReviewOutput(_) => "WatcherReviewOutput",

            StreamTypes::WebSearchToolArgs(_) => "WebSearchToolArgs",

            StreamTypes::WriteFileToolArgs(_) => "WriteFileToolArgs",
        }
    }
}
