#!/usr/bin/env bash
# Generate docs/ATLAS.md from frontmatter across practice/, theory/, state/
# Run: ./scripts/generate-atlas.sh
# Also runs as pre-commit hook to keep atlas fresh.

set -euo pipefail
DOCS_DIR="$(cd "$(dirname "$0")/../docs" && pwd)"
ATLAS="$DOCS_DIR/ATLAS.md"

# Parse frontmatter field from a file. Usage: fm_field <file> <field>
fm_field() {
  local file="$1" field="$2"
  head -15 "$file" | sed -n "s/^${field}: *//p" | head -1
}

# Extract title from first H1 line
fm_title() {
  head -5 "$1" | sed -n 's/^# *//p' | head -1
}

# Collect doc metadata into arrays
declare -a DOC_PATHS DOC_TITLES DOC_KINDS DOC_STATUSES DOC_PRIORITIES DOC_REQUIRES
idx=0

scan_dir() {
  local dir="$1"
  if [ ! -d "$dir" ]; then return; fi
  while IFS= read -r -d '' file; do
    local rel="${file#$DOCS_DIR/}"
    local title kind status priority requires
    title="$(fm_title "$file")"
    kind="$(fm_field "$file" "Kind")"
    status="$(fm_field "$file" "Status")"
    priority="$(fm_field "$file" "Priority")"
    requires="$(fm_field "$file" "Requires")"
    [ -z "$title" ] && title="$(basename "$file" .md)"
    [ -z "$priority" ] && priority="5"
    DOC_PATHS[$idx]="$rel"
    DOC_TITLES[$idx]="$title"
    DOC_KINDS[$idx]="$kind"
    DOC_STATUSES[$idx]="$status"
    DOC_PRIORITIES[$idx]="$priority"
    DOC_REQUIRES[$idx]="$requires"
    idx=$((idx + 1))
  done < <(find "$dir" -name '*.md' -print0 | sort -z)
}

scan_dir "$DOCS_DIR/practice"
scan_dir "$DOCS_DIR/theory"
scan_dir "$DOCS_DIR/state"

# --- Helper: emit sorted section ---
emit_section() {
  local match_prefix="$1" header="$2" show_priority="$3" is_open="$4"

  if [ "$is_open" = "true" ]; then
    printf "<details open>\n<summary><h2>%s</h2></summary>\n\n" "$header"
  else
    printf "<details>\n<summary><h2>%s</h2></summary>\n\n" "$header"
  fi

  local section_indices=()
  for i in $(seq 0 $((idx - 1))); do
    case "${DOC_PATHS[$i]}" in ${match_prefix}*) section_indices+=("$i") ;; esac
  done

  # Sort by priority
  for ((a=1; a<${#section_indices[@]}; a++)); do
    key=${section_indices[$a]}
    b=$((a - 1))
    while [ $b -ge 0 ] && [ "${DOC_PRIORITIES[${section_indices[$b]}]}" -gt "${DOC_PRIORITIES[$key]}" ] 2>/dev/null; do
      section_indices[$((b + 1))]=${section_indices[$b]}
      b=$((b - 1))
    done
    section_indices[$((b + 1))]=$key
  done

  local has_items=false
  for i in "${section_indices[@]}"; do
    has_items=true
    local_req="${DOC_REQUIRES[$i]}"
    req_str=""
    [ -n "$local_req" ] && [ "$local_req" != "[]" ] && req_str=" | Requires: $local_req"
    if [ "$show_priority" = "true" ]; then
      printf -- "- **[P%s]** %s — %s (%s)%s  \n  \`docs/%s\`\n" \
        "${DOC_PRIORITIES[$i]}" "${DOC_TITLES[$i]}" "${DOC_KINDS[$i]:-?}" "${DOC_STATUSES[$i]:-?}" "$req_str" "${DOC_PATHS[$i]}"
    else
      printf -- "- %s — %s (%s)%s  \n  \`docs/%s\`\n" \
        "${DOC_TITLES[$i]}" "${DOC_KINDS[$i]:-?}" "${DOC_STATUSES[$i]:-?}" "$req_str" "${DOC_PATHS[$i]}"
    fi
  done
  $has_items || echo "_Empty._"
  echo ""
  echo "</details>"
  echo ""
}

# --- Emit ATLAS.md ---
{
cat <<'HEADER'
# ChoirOS Atlas

> Auto-generated by `scripts/generate-atlas.sh`. Do not edit manually.
> Re-run: `just atlas` or commit (pre-commit hook).

## Where We Are

ChoirOS is a multi-agent runtime built on ractor supervision trees.
Agents (conductor, writer, researcher, terminal) run inside per-user
MicroVMs on OVH bare metal, fronted by a hypervisor control plane
that handles auth, provider gateway, and VM lifecycle.

**Current state:** Two OVH nodes running. CI/CD deploys to Node A.
Sandbox runs inside a cloud-hypervisor VM with virtiofs shares.
Writer, researcher, and terminal agents are functional. Conductor
orchestrates via model-led control flow.

**Critical blocker:** VM state is lost on idle watchdog restart —
no snapshotting or persistent volumes yet (see ADR-0014 for the plan).

**Where we're going:** Fix VM persistence, then build fleet-ctl for
change lifecycle and promotion (ADR-0013), per-user storage isolation
(ADR-0014), and an orchestration layer between conductor and long-lived
agent sessions.

HEADER

emit_section "theory/" "Theory (What We're Thinking)" "true" "true"
emit_section "practice/" "Practice (What Exists)" "false" "false"
emit_section "state/" "State (Snapshots & Reports)" "false" "false"

# --- Dependency Graph ---
echo "## Dependency Graph"
echo ""
echo '```'
has_deps=false
for i in $(seq 0 $((idx - 1))); do
  local_req="${DOC_REQUIRES[$i]}"
  if [ -n "$local_req" ] && [ "$local_req" != "[]" ]; then
    has_deps=true
    clean_req="$(echo "$local_req" | tr -d '[]')"
    printf "%s → %s\n" "$clean_req" "${DOC_TITLES[$i]}"
  fi
done
$has_deps || echo "(no dependencies declared yet)"
echo '```'
echo ""

# --- Stats ---
practice_count=0; theory_count=0; state_count=0
for i in $(seq 0 $((idx - 1))); do
  case "${DOC_PATHS[$i]}" in
    practice/*) practice_count=$((practice_count + 1)) ;;
    theory/*) theory_count=$((theory_count + 1)) ;;
    state/*) state_count=$((state_count + 1)) ;;
  esac
done
printf "*Generated %s — %d practice, %d theory, %d state docs.*\n" \
  "$(date +%Y-%m-%d)" "$practice_count" "$theory_count" "$state_count"

} > "$ATLAS"

echo "atlas: wrote $ATLAS ($idx docs scanned)"
