#!/usr/bin/env bash
# Generate docs/ATLAS.md from frontmatter across theory/, practice/, state/
# Run: ./scripts/generate-atlas.sh
# Also runs as pre-commit hook to keep atlas fresh.

set -euo pipefail
DOCS_DIR="$(cd "$(dirname "$0")/../docs" && pwd)"
ATLAS="$DOCS_DIR/ATLAS.md"

# Parse frontmatter field from a file. Usage: fm_field <file> <field>
fm_field() {
  local file="$1" field="$2"
  # Match "Field: value" in the first 15 lines (frontmatter zone)
  head -15 "$file" | sed -n "s/^${field}: *//p" | head -1
}

# Extract title from first H1 line
fm_title() {
  head -5 "$1" | sed -n 's/^# *//p' | head -1
}

# Collect doc metadata into arrays
declare -a DOC_PATHS DOC_TITLES DOC_KINDS DOC_STATUSES DOC_PRIORITIES DOC_REQUIRES
idx=0

scan_dir() {
  local dir="$1"
  if [ ! -d "$dir" ]; then return; fi
  while IFS= read -r -d '' file; do
    local rel="${file#$DOCS_DIR/}"
    local title kind status priority requires
    title="$(fm_title "$file")"
    kind="$(fm_field "$file" "Kind")"
    status="$(fm_field "$file" "Status")"
    priority="$(fm_field "$file" "Priority")"
    requires="$(fm_field "$file" "Requires")"
    [ -z "$title" ] && title="$(basename "$file" .md)"
    [ -z "$priority" ] && priority="5"
    DOC_PATHS[$idx]="$rel"
    DOC_TITLES[$idx]="$title"
    DOC_KINDS[$idx]="$kind"
    DOC_STATUSES[$idx]="$status"
    DOC_PRIORITIES[$idx]="$priority"
    DOC_REQUIRES[$idx]="$requires"
    idx=$((idx + 1))
  done < <(find "$dir" -name '*.md' -print0 | sort -z)
}

scan_dir "$DOCS_DIR/practice"
scan_dir "$DOCS_DIR/theory"
scan_dir "$DOCS_DIR/state"

# --- Emit ATLAS.md ---
{
cat <<'HEADER'
# ChoirOS Atlas

> Auto-generated by `scripts/generate-atlas.sh`. Do not edit manually.
> Re-run: `just atlas` or commit (pre-commit hook).

## System at a Glance

ChoirOS is a supervision-tree-first multi-agent runtime. Local-first reliability,
then OVH US-East bootstrap with strict control-plane secrets boundaries.

**Quick start:**
```bash
just local-build-ui && just dev
# Open http://127.0.0.1:9090/login
```

HEADER

# --- Theory: thinking, proposing, exploring (listed first — this is where attention goes) ---
echo "## Theory (Thinking / Proposing)"
echo ""

# Sort theory docs by priority (lower = higher priority)
theory_indices=()
for i in $(seq 0 $((idx - 1))); do
  case "${DOC_PATHS[$i]}" in theory/*) theory_indices+=("$i") ;; esac
done

# Simple insertion sort by priority
for ((a=1; a<${#theory_indices[@]}; a++)); do
  key=${theory_indices[$a]}
  b=$((a - 1))
  while [ $b -ge 0 ] && [ "${DOC_PRIORITIES[${theory_indices[$b]}]}" -gt "${DOC_PRIORITIES[$key]}" ] 2>/dev/null; do
    theory_indices[$((b + 1))]=${theory_indices[$b]}
    b=$((b - 1))
  done
  theory_indices[$((b + 1))]=$key
done

has_theory=false
for i in "${theory_indices[@]}"; do
  has_theory=true
  local_req="${DOC_REQUIRES[$i]}"
  req_str=""
  [ -n "$local_req" ] && [ "$local_req" != "[]" ] && req_str=" | Requires: $local_req"
  printf -- "- **[P%s]** %s — %s (%s)%s  \n  \`docs/%s\`\n" \
    "${DOC_PRIORITIES[$i]}" "${DOC_TITLES[$i]}" "${DOC_KINDS[$i]:-?}" "${DOC_STATUSES[$i]:-?}" "$req_str" "${DOC_PATHS[$i]}"
done
$has_theory || echo "_No theory docs._"
echo ""

# --- Practice: in use, partially or fully implemented ---
echo "## Practice (In Use / Being Built)"
echo ""
has_practice=false
for i in $(seq 0 $((idx - 1))); do
  case "${DOC_PATHS[$i]}" in practice/*) has_practice=true ;; *) continue ;; esac
  printf -- "- **%s** — %s (%s)  \n  \`docs/%s\`\n" \
    "${DOC_TITLES[$i]}" "${DOC_KINDS[$i]:-?}" "${DOC_STATUSES[$i]:-?}" "${DOC_PATHS[$i]}"
done
$has_practice || echo "_No practice docs yet._"
echo ""

# --- State: Execution Artifacts ---
echo "## State (Snapshots & Reports)"
echo ""
has_state=false
for i in $(seq 0 $((idx - 1))); do
  case "${DOC_PATHS[$i]}" in state/*) has_state=true ;; *) continue ;; esac
  printf -- "- %s — %s (%s)  \n  \`docs/%s\`\n" \
    "${DOC_TITLES[$i]}" "${DOC_KINDS[$i]:-?}" "${DOC_STATUSES[$i]:-?}" "${DOC_PATHS[$i]}"
done
$has_state || echo "_No state docs yet._"
echo ""

# --- Dependency Graph ---
echo "## Dependency Graph"
echo ""
echo '```'
has_deps=false
for i in $(seq 0 $((idx - 1))); do
  local_req="${DOC_REQUIRES[$i]}"
  if [ -n "$local_req" ] && [ "$local_req" != "[]" ]; then
    has_deps=true
    # Clean brackets: [ADR-0013, ADR-0014] → ADR-0013, ADR-0014
    clean_req="$(echo "$local_req" | tr -d '[]')"
    printf "%s → %s\n" "$clean_req" "${DOC_TITLES[$i]}"
  fi
done
$has_deps || echo "(no dependencies declared yet)"
echo '```'
echo ""

# --- Stats ---
practice_count=0; theory_count=0; state_count=0
for i in $(seq 0 $((idx - 1))); do
  case "${DOC_PATHS[$i]}" in
    practice/*) practice_count=$((practice_count + 1)) ;;
    theory/*) theory_count=$((theory_count + 1)) ;;
    state/*) state_count=$((state_count + 1)) ;;
  esac
done
printf "*Generated %s — %d practice, %d theory, %d state docs.*\n" \
  "$(date +%Y-%m-%d)" "$practice_count" "$theory_count" "$state_count"

} > "$ATLAS"

echo "atlas: wrote $ATLAS ($idx docs scanned)"
