// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
pub(crate) mod enums;
mod type_aliases;
mod unions;

pub use classes::{
    AgentDecision, AgentToolArgs, AgentToolCall, BashToolArgs, ConductorBootstrapInput,
    ConductorBootstrapOutput, ConductorDecision, ConductorDecisionInput,
    ConductorObjectiveRefineInput, ConductorObjectiveRefineOutput, ListFilesToolArgs, Message,
    ReadFileToolArgs, ResearcherPlanInput, ResearcherPlanOutput, Resume, SearchFilesToolArgs,
    StreamChunk, ToolResult, WebSearchToolArgs, WriteFileToolArgs,
};
pub use enums::{Action, ConductorAction, ResearchAction, ResearchStatus};
pub use type_aliases::*;
pub use unions::*;

// Re-export types from baml runtime
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone)]
pub enum Types {
    AgentDecision(AgentDecision),

    AgentToolArgs(AgentToolArgs),

    AgentToolCall(AgentToolCall),

    BashToolArgs(BashToolArgs),

    ConductorBootstrapInput(ConductorBootstrapInput),

    ConductorBootstrapOutput(ConductorBootstrapOutput),

    ConductorDecision(ConductorDecision),

    ConductorDecisionInput(ConductorDecisionInput),

    ConductorObjectiveRefineInput(ConductorObjectiveRefineInput),

    ConductorObjectiveRefineOutput(ConductorObjectiveRefineOutput),

    ListFilesToolArgs(ListFilesToolArgs),

    Message(Message),

    ReadFileToolArgs(ReadFileToolArgs),

    ResearcherPlanInput(ResearcherPlanInput),

    ResearcherPlanOutput(ResearcherPlanOutput),

    Resume(Resume),

    SearchFilesToolArgs(SearchFilesToolArgs),

    StreamChunk(StreamChunk),

    ToolResult(ToolResult),

    WebSearchToolArgs(WebSearchToolArgs),

    WriteFileToolArgs(WriteFileToolArgs),

    Action(Action),

    ConductorAction(ConductorAction),

    ResearchAction(ResearchAction),

    ResearchStatus(ResearchStatus),
}

impl baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            Types::AgentDecision(_) => "AgentDecision",

            Types::AgentToolArgs(_) => "AgentToolArgs",

            Types::AgentToolCall(_) => "AgentToolCall",

            Types::BashToolArgs(_) => "BashToolArgs",

            Types::ConductorBootstrapInput(_) => "ConductorBootstrapInput",

            Types::ConductorBootstrapOutput(_) => "ConductorBootstrapOutput",

            Types::ConductorDecision(_) => "ConductorDecision",

            Types::ConductorDecisionInput(_) => "ConductorDecisionInput",

            Types::ConductorObjectiveRefineInput(_) => "ConductorObjectiveRefineInput",

            Types::ConductorObjectiveRefineOutput(_) => "ConductorObjectiveRefineOutput",

            Types::ListFilesToolArgs(_) => "ListFilesToolArgs",

            Types::Message(_) => "Message",

            Types::ReadFileToolArgs(_) => "ReadFileToolArgs",

            Types::ResearcherPlanInput(_) => "ResearcherPlanInput",

            Types::ResearcherPlanOutput(_) => "ResearcherPlanOutput",

            Types::Resume(_) => "Resume",

            Types::SearchFilesToolArgs(_) => "SearchFilesToolArgs",

            Types::StreamChunk(_) => "StreamChunk",

            Types::ToolResult(_) => "ToolResult",

            Types::WebSearchToolArgs(_) => "WebSearchToolArgs",

            Types::WriteFileToolArgs(_) => "WriteFileToolArgs",

            Types::Action(_) => "Action",

            Types::ConductorAction(_) => "ConductorAction",

            Types::ResearchAction(_) => "ResearchAction",

            Types::ResearchStatus(_) => "ResearchStatus",
        }
    }
}
