// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod type_aliases;
mod unions;

pub use classes::*;
pub use enums::*;
pub use type_aliases::*;
pub use unions::*;

// Re-export types from baml runtime
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone)]
pub enum Types {
    AgentPlan(AgentPlan),

    AgentToolArgs(AgentToolArgs),

    AgentToolCall(AgentToolCall),

    BashToolArgs(BashToolArgs),

    CompletionPayload(CompletionPayload),

    Evidence(Evidence),

    ListFilesToolArgs(ListFilesToolArgs),

    Message(Message),

    NextAction(NextAction),

    ObjectiveContract(ObjectiveContract),

    ReadFileToolArgs(ReadFileToolArgs),

    Resume(Resume),

    SearchFilesToolArgs(SearchFilesToolArgs),

    StreamChunk(StreamChunk),

    ToolResult(ToolResult),

    UnresolvedItem(UnresolvedItem),

    WebSearchToolArgs(WebSearchToolArgs),

    WriteFileToolArgs(WriteFileToolArgs),

    EvidenceType(EvidenceType),

    NextActionType(NextActionType),

    ObjectiveStatus(ObjectiveStatus),

    PlanMode(PlanMode),
}

impl baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {
            Types::AgentPlan(_) => "AgentPlan",

            Types::AgentToolArgs(_) => "AgentToolArgs",

            Types::AgentToolCall(_) => "AgentToolCall",

            Types::BashToolArgs(_) => "BashToolArgs",

            Types::CompletionPayload(_) => "CompletionPayload",

            Types::Evidence(_) => "Evidence",

            Types::ListFilesToolArgs(_) => "ListFilesToolArgs",

            Types::Message(_) => "Message",

            Types::NextAction(_) => "NextAction",

            Types::ObjectiveContract(_) => "ObjectiveContract",

            Types::ReadFileToolArgs(_) => "ReadFileToolArgs",

            Types::Resume(_) => "Resume",

            Types::SearchFilesToolArgs(_) => "SearchFilesToolArgs",

            Types::StreamChunk(_) => "StreamChunk",

            Types::ToolResult(_) => "ToolResult",

            Types::UnresolvedItem(_) => "UnresolvedItem",

            Types::WebSearchToolArgs(_) => "WebSearchToolArgs",

            Types::WriteFileToolArgs(_) => "WriteFileToolArgs",

            Types::EvidenceType(_) => "EvidenceType",

            Types::NextActionType(_) => "NextActionType",

            Types::ObjectiveStatus(_) => "ObjectiveStatus",

            Types::PlanMode(_) => "PlanMode",
        }
    }
}
