// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated BAML types.

mod classes;
mod enums;
mod unions;
mod type_aliases;

pub use classes::*;
pub use enums::*;
pub use unions::*;
pub use type_aliases::*;

// Re-export types from baml runtime
pub use baml::{Audio, Image, Pdf, Video};
pub use baml::{Checked, StreamState};

/// All known types in this BAML project.
/// Serves as the compile-time type registry for BamlValue.
#[derive(Debug, Clone)]
pub enum Types {

    AgentDecision(AgentDecision),

    AgentToolArgs(AgentToolArgs),

    AgentToolCall(AgentToolCall),

    AlternativeAction(AlternativeAction),

    BashToolArgs(BashToolArgs),

    ConductorAgendaItem(ConductorAgendaItem),

    ConductorArtifact(ConductorArtifact),

    ConductorBootstrapInput(ConductorBootstrapInput),

    ConductorBootstrapOutput(ConductorBootstrapOutput),

    ConductorCapabilityCall(ConductorCapabilityCall),

    ConductorDecisionInput(ConductorDecisionInput),

    ConductorDecisionOutput(ConductorDecisionOutput),

    ConductorObjectiveRefineInput(ConductorObjectiveRefineInput),

    ConductorObjectiveRefineOutput(ConductorObjectiveRefineOutput),

    ConductorTerminalityInput(ConductorTerminalityInput),

    ConductorTerminalityOutput(ConductorTerminalityOutput),

    DetectedAnomaly(DetectedAnomaly),

    EventSummary(EventSummary),

    FollowupRecommendation(FollowupRecommendation),

    HistoricalResolution(HistoricalResolution),

    ListFilesToolArgs(ListFilesToolArgs),

    Message(Message),

    ReadFileToolArgs(ReadFileToolArgs),

    ResearcherPlanInput(ResearcherPlanInput),

    ResearcherPlanOutput(ResearcherPlanOutput),

    Resume(Resume),

    RetryPolicy(RetryPolicy),

    ReviewScope(ReviewScope),

    RiskItem(RiskItem),

    RunStateSnapshot(RunStateSnapshot),

    SearchFilesToolArgs(SearchFilesToolArgs),

    StreamChunk(StreamChunk),

    ToolResult(ToolResult),

    WatcherEscalation(WatcherEscalation),

    WatcherEvent(WatcherEvent),

    WatcherLogWindowInput(WatcherLogWindowInput),

    WatcherMitigationInput(WatcherMitigationInput),

    WatcherMitigationOutput(WatcherMitigationOutput),

    WatcherReviewOutput(WatcherReviewOutput),

    WebSearchToolArgs(WebSearchToolArgs),

    WorkerOutput(WorkerOutput),

    WriteFileToolArgs(WriteFileToolArgs),


    Action(Action),

    DecisionType(DecisionType),

    EscalationAction(EscalationAction),

    EscalationKind(EscalationKind),

    ResearchAction(ResearchAction),

    ResearchStatus(ResearchStatus),

    ReviewStatus(ReviewStatus),

    RiskCategory(RiskCategory),

    TerminalityStatus(TerminalityStatus),

    UrgencyLevel(UrgencyLevel),


}

impl baml::KnownTypes for Types {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            Types::AgentDecision(_) => "AgentDecision",

            Types::AgentToolArgs(_) => "AgentToolArgs",

            Types::AgentToolCall(_) => "AgentToolCall",

            Types::AlternativeAction(_) => "AlternativeAction",

            Types::BashToolArgs(_) => "BashToolArgs",

            Types::ConductorAgendaItem(_) => "ConductorAgendaItem",

            Types::ConductorArtifact(_) => "ConductorArtifact",

            Types::ConductorBootstrapInput(_) => "ConductorBootstrapInput",

            Types::ConductorBootstrapOutput(_) => "ConductorBootstrapOutput",

            Types::ConductorCapabilityCall(_) => "ConductorCapabilityCall",

            Types::ConductorDecisionInput(_) => "ConductorDecisionInput",

            Types::ConductorDecisionOutput(_) => "ConductorDecisionOutput",

            Types::ConductorObjectiveRefineInput(_) => "ConductorObjectiveRefineInput",

            Types::ConductorObjectiveRefineOutput(_) => "ConductorObjectiveRefineOutput",

            Types::ConductorTerminalityInput(_) => "ConductorTerminalityInput",

            Types::ConductorTerminalityOutput(_) => "ConductorTerminalityOutput",

            Types::DetectedAnomaly(_) => "DetectedAnomaly",

            Types::EventSummary(_) => "EventSummary",

            Types::FollowupRecommendation(_) => "FollowupRecommendation",

            Types::HistoricalResolution(_) => "HistoricalResolution",

            Types::ListFilesToolArgs(_) => "ListFilesToolArgs",

            Types::Message(_) => "Message",

            Types::ReadFileToolArgs(_) => "ReadFileToolArgs",

            Types::ResearcherPlanInput(_) => "ResearcherPlanInput",

            Types::ResearcherPlanOutput(_) => "ResearcherPlanOutput",

            Types::Resume(_) => "Resume",

            Types::RetryPolicy(_) => "RetryPolicy",

            Types::ReviewScope(_) => "ReviewScope",

            Types::RiskItem(_) => "RiskItem",

            Types::RunStateSnapshot(_) => "RunStateSnapshot",

            Types::SearchFilesToolArgs(_) => "SearchFilesToolArgs",

            Types::StreamChunk(_) => "StreamChunk",

            Types::ToolResult(_) => "ToolResult",

            Types::WatcherEscalation(_) => "WatcherEscalation",

            Types::WatcherEvent(_) => "WatcherEvent",

            Types::WatcherLogWindowInput(_) => "WatcherLogWindowInput",

            Types::WatcherMitigationInput(_) => "WatcherMitigationInput",

            Types::WatcherMitigationOutput(_) => "WatcherMitigationOutput",

            Types::WatcherReviewOutput(_) => "WatcherReviewOutput",

            Types::WebSearchToolArgs(_) => "WebSearchToolArgs",

            Types::WorkerOutput(_) => "WorkerOutput",

            Types::WriteFileToolArgs(_) => "WriteFileToolArgs",


            Types::Action(_) => "Action",

            Types::DecisionType(_) => "DecisionType",

            Types::EscalationAction(_) => "EscalationAction",

            Types::EscalationKind(_) => "EscalationKind",

            Types::ResearchAction(_) => "ResearchAction",

            Types::ResearchStatus(_) => "ResearchStatus",

            Types::ReviewStatus(_) => "ReviewStatus",

            Types::RiskCategory(_) => "RiskCategory",

            Types::TerminalityStatus(_) => "TerminalityStatus",

            Types::UrgencyLevel(_) => "UrgencyLevel",



        }
    }
}