// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated union types.

use baml::{BamlEncode, BamlDecode};
use super::*;


/// Generated from: (BashToolCall | WebSearchToolCall | FetchUrlToolCall | FileReadToolCall | FileWriteToolCall | FileEditToolCall | MessageWriterToolCall | FinishedToolCall)
#[derive(Debug, Clone, BamlEncode, BamlDecode)]
#[baml(union)]
pub enum Union8BashToolCallOrFetchUrlToolCallOrFileEditToolCallOrFileReadToolCallOrFileWriteToolCallOrFinishedToolCallOrMessageWriterToolCallOrWebSearchToolCall {

    #[baml(name = "BashToolCall")]
        BashToolCall(BashToolCall),
    
    #[baml(name = "WebSearchToolCall")]
        WebSearchToolCall(WebSearchToolCall),
    
    #[baml(name = "FetchUrlToolCall")]
        FetchUrlToolCall(FetchUrlToolCall),
    
    #[baml(name = "FileReadToolCall")]
        FileReadToolCall(FileReadToolCall),
    
    #[baml(name = "FileWriteToolCall")]
        FileWriteToolCall(FileWriteToolCall),
    
    #[baml(name = "FileEditToolCall")]
        FileEditToolCall(FileEditToolCall),
    
    #[baml(name = "MessageWriterToolCall")]
        MessageWriterToolCall(MessageWriterToolCall),
    
    #[baml(name = "FinishedToolCall")]
        FinishedToolCall(FinishedToolCall),
    
}

impl AsRef<Union8BashToolCallOrFetchUrlToolCallOrFileEditToolCallOrFileReadToolCallOrFileWriteToolCallOrFinishedToolCallOrMessageWriterToolCallOrWebSearchToolCall> for Union8BashToolCallOrFetchUrlToolCallOrFileEditToolCallOrFileReadToolCallOrFileWriteToolCallOrFinishedToolCallOrMessageWriterToolCallOrWebSearchToolCall {
    fn as_ref(&self) -> &Union8BashToolCallOrFetchUrlToolCallOrFileEditToolCallOrFileReadToolCallOrFileWriteToolCallOrFinishedToolCallOrMessageWriterToolCallOrWebSearchToolCall {
        self
    }
}

impl Default for Union8BashToolCallOrFetchUrlToolCallOrFileEditToolCallOrFileReadToolCallOrFileWriteToolCallOrFinishedToolCallOrMessageWriterToolCallOrWebSearchToolCall {
    fn default() -> Self {
        
           
            Self::BashToolCall(Default::default())
        
    }
}

